# -*- coding: utf-8 -*-
"""碳足跡計算系統.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YY88HPpBXV7BtUq3Rv0_DKZw79D9h1jJ
"""

def main():
    factors = {
        "car": 200,
        "scooter": 60,
        "bag": 57,
        "utensils": 40,
        "cup": 25,
        "box": 80,
        "straw": 5
    }

    print("=" * 45)
    print("        EcoLife 碳足跡計算系統")
    print("=" * 45)

    total_carbon = 0

    while True:
        print("\n" + "-" * 45)
        print("【主選單】")
        print("1 → 交通里程")
        print("2 → 拋棄式耗材")
        print("3 → 查看結果並結束")
        print("-" * 45)

        choice = input("請選擇 (1/2/3)：")

        # ===== 交通 =====
        if choice == '1':
            print("\n【交通里程輸入】")
            print("1 → 汽車 (200 g/km)")
            print("2 → 機車 (60 g/km)")

            v = input("請選擇交通工具：")

            if v == '1':
                vehicle = "car"
            elif v == '2':
                vehicle = "scooter"
            else:
                print("⚠️ 輸入錯誤")
                continue

            try:
                km = float(input("請輸入公里數："))
                subtotal = km * factors[vehicle]
                total_carbon += subtotal

                print("-" * 30)
                print("本次碳排放：", subtotal, "gCO2e")
                print("目前累積：", total_carbon, "gCO2e")
                print("-" * 30)

            except:
                print("⚠️ 請輸入正確數字")

        # ===== 耗材 =====
        elif choice == '2':
            print("\n【耗材輸入】")
            print("1 → 塑膠袋 (57 g)")
            print("2 → 免洗餐具 (40 g)")
            print("3 → 紙杯 (25 g)")
            print("4 → 紙餐盒 (80 g)")
            print("5 → 吸管 (5 g)")

            item = input("請選擇項目：")

            if item == '1':
                item_type = "bag"
            elif item == '2':
                item_type = "utensils"
            elif item == '3':
                item_type = "cup"
            elif item == '4':
                item_type = "box"
            elif item == '5':
                item_type = "straw"
            else:
                print("⚠️ 輸入錯誤")
                continue

            try:
                count = int(input("請輸入數量："))
                subtotal = count * factors[item_type]
                total_carbon += subtotal

                print("-" * 30)
                print("本次碳排放：", subtotal, "gCO2e")
                print("目前累積：", total_carbon, "gCO2e")
                print("-" * 30)

            except:
                print("⚠️ 請輸入正確整數")

        # ===== 結束 =====
        elif choice == '3':
            break

        else:
            print("⚠️ 請輸入正確選項")

    # ===== 結果區 =====
    print("\n" + "=" * 45)
    print("           【今日碳排總結】")
    print("=" * 45)

    print("總碳排放量：", total_carbon, "gCO2e")

    threshold = 2000

    if total_carbon > threshold:
        print("\n⚠️ 碳排偏高")
        print("建議：減少一次性用品 / 搭乘大眾運輸")
    else:
        print("\n🌱 表現良好")
        print("你正在降低對環境的影響！")

    print("\n" + "-" * 45)
    print("【生科觀點】")

    trees = round(total_carbon / 33, 2)
    print("需約", trees, "棵樹一天吸收這些 CO2")
    print("塑膠可能轉為微塑膠，影響生物與食物鏈")
    print("=" * 45)


if __name__ == "__main__":
    main()